workflow update

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -24,19 +24,27 @@ jobs:
     - name: Build plugin
       run: node esbuild.config.mjs production
 
+    - name: Check if flylighter directory exists
+      run: |
+        if [ ! -d "flylighter" ]; then
+          echo "Error: Directory 'flylighter' does not exist."
+          exit 1
+        fi
+
+    - name: Get version
+      id: extract_version
+      run: echo "::set-output name=version::$(jq -r '.version' manifest.json)"
+
     - name: Zip build folder
       run: |
-        version=$(jq -r '.version' manifest.json)
+        version=${{ steps.extract_version.outputs.version }}
         zip -r "flylighter_obsidian-plugin_${version}.zip" flylighter
 
-    - name: Upload release asset
-      id: upload-release-asset
-      uses: actions/upload-release-asset@v1
+    - name: Upload build artifact
+      uses: actions/upload-artifact@v2
       with:
-        upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: ./flylighter_obsidian-plugin_${{ steps.import_version.outputs.version }}.zip
-        asset_name: flylighter_obsidian-plugin_${{ steps.import_version.outputs.version }}.zip
-        asset_content_type: application/zip
+        name: build-zip
+        path: flylighter_obsidian-plugin_${{ steps.extract_version.outputs.version }}.zip
 
   release:
     needs: build
@@ -50,6 +58,19 @@ jobs:
       uses: actions/setup-node@v2
       with:
         node-version: '16'
+
+    - name: Get version
+      id: extract_version
+      run: echo "::set-output name=version::$(jq -r '.version' manifest.json)"
+
+    - name: Get merge commit messages
+      id: get_commits
+      run: echo "::set-output name=commits::$(git log --merges -1 --pretty=format:'%b')"
+
+    - name: Download build artifact
+      uses: actions/download-artifact@v2
+      with:
+        name: build-zip
 
     - name: Create Release
       id: create_release
@@ -65,10 +86,11 @@ jobs:
         draft: false
         prerelease: false
 
-    - name: Get version
-      id: extract_version
-      run: echo "::set-output name=version::$(jq -r '.version' manifest.json)"
-
-    - name: Get merge commit messages
-      id: get_commits
-      run: echo "::set-output name=commits::$(git log --merges -1 --pretty=format:'%b')"
+    - name: Upload release asset
+      id: upload-release-asset
+      uses: actions/upload-release-asset@v1
+      with:
+        upload_url: ${{ steps.create_release.outputs.upload_url }}
+        asset_path: ./flylighter_obsidian-plugin_${{ steps.extract_version.outputs.version }}.zip
+        asset_name: flylighter_obsidian-plugin_${{ steps.extract_version.outputs.version }}.zip
+        asset_content_type: application/zip
